const cities = [
    {   id: 0,
      city: '',
      country: '',
    },
    {   id: 1,
        city: 'New York City',
        country: 'United States',
      },
      { id: 2,
        city: 'Hong Kong',
        country: 'China',
      },
      { id: 3,
        city: 'Chicago',
        country: 'United States',
      },
      { id: 4,
        city: 'Tokyo',
        country: 'Japan',
      },
      { id: 5,
        city: 'Seul',
        country: 'South Korea',
      },
      { id: 6,
        city: 'Shanghai',
        country: 'China',
      },
      { id: 7,
        city: 'Singapore',
        country: 'Singapore',
      },
      { id: 8,
        city: 'Sydney',
        country: 'Australia',
      },
      { id: 9,
        city: 'San Francisco',
        country: 'United States',
      },
      { id: 10,
        city: 'Madrid',
        country: 'Spain',
      },
      { id: 11,
        city: 'Buenos Aires',
        country: 'Argentina',
      },
      { id: 12,
        city: 'Los Angeles',
        country: 'United States',
      },
      { id: 13,
        city: 'Rome',
        country: 'Italy',
      },
      { id: 14,
        city: 'Paris',
        country: 'France',
      },
      { id: 15,
        city: 'London',
        country: 'United Kingdom',
      },
]

export default cities